<?php

use Drupal\Core\Render\Markup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Adds JS/CSS to all pages for admin users.
 */
function gin_custom_page_attachments_alter(&$page) {
  if (_gin_toolbar_gin_is_active()) {
    $page['#attached']['library'][] = 'gin_custom/toolbar';
  }

  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $page['#attached']['library'][] = 'gin_custom/admin';
  }
}

/**
 * Add a dark mode setting for Gin toolbar on all non-Gin themes.
 */
function gin_custom_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id = NULL)
{
  if (!_gin_toolbar_gin_is_active()) {
    return;
  }
  $themeToBeConfigured = $form_state->getBuildInfo()['args'][0];
  if (!$themeToBeConfigured) {
    return;
  }
  if ($themeToBeConfigured == 'gin') {
    return;
  }

  $form['gin_toolbar_force_darkmode'] = [
    '#type' => 'checkbox',
    '#title' => t('Gin toolbar dark mode'),
    '#default_value' => theme_get_setting('gin_toolbar_force_darkmode', $themeToBeConfigured),
  ];
}

/**
 * Inject dark mode for Gin toolbar on non-Gin themes
 */
function gin_custom_preprocess_html(&$variables) {
  if (!_gin_toolbar_gin_is_active()) {
    return;
  }

  $currentTheme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if ($currentTheme == 'gin' || !(theme_get_setting('gin_toolbar_force_darkmode', $currentTheme) ?? FALSE)) {
    return;
  }

  $variables['attributes']['class'][] = 'gin--dark-mode';
}

/**
 * Wraps views exposed filter forms inside a collapsable <details> element.
 */
function gin_custom_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $nonDefaultFilters = [];
  foreach ($form_state->getUserInput() as $key => $value) {
    if ($value != $form[$key]['#default_value']) {
      $nonDefaultFilters[] = $form['#info']["filter-{$key}"]['label'];
    }
  }

  $prefix = '<details class="claro-details"><summary class="claro-details__summary">';
  if (!empty($nonDefaultFilters)) {
    $prefix .= t('Modified filters: @filters', ['@filters' => join(', ', $nonDefaultFilters)])->render();
  }
  else {
    $prefix .= t('Filter')->render();
  }
  $prefix .= '</summary>';
  $form['#prefix'] = Markup::create($prefix);
  $form['#suffix'] = Markup::create('</details>');
  $form['#attached']['library'][] = 'gin_custom/admin';
}
