<?php

use Drupal\Core\Render\Markup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Adds toolbar JS/CSS to all pages for admin users.
 */
function gin_custom_page_attachments_alter(&$page) {
  if (!_gin_toolbar_gin_is_active()) {
    return;
  }

  $page['#attached']['library'][] = 'gin_custom/toolbar';
}



/**
 * Wraps views exposed filter forms inside a collapsable <details> element.
 */
function gin_custom_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $nonDefaultFilters = [];
  foreach ($form_state->getUserInput() as $key => $value) {
    if ($value != $form[$key]['#default_value']) {
      $nonDefaultFilters[] = $form['#info']["filter-{$key}"]['label'];
    }
  }

  $prefix = '<details class="claro-details"><summary class="claro-details__summary">';
  if (!empty($nonDefaultFilters)) {
    $prefix .= t('Modified filters: @filters', ['@filters' => join(', ', $nonDefaultFilters)])->render();
  }
  else {
    $prefix .= t('Filter')->render();
  }
  $prefix .= '</summary>';
  $form['#prefix'] = Markup::create($prefix);
  $form['#suffix'] = Markup::create('</details>');
  $form['#attached']['library'][] = 'gin_custom/admin';
}
